openapi: 3.0.1
info:
  title: Common Type Definitions as proxy reference
  version: 17.0.0
  description: >-
    OAS 3.0.1 specification of common type definitions in the Generic NRM
    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
externalDocs:
  description: This is CT common datatype proxy
  url: nn
paths: {}
components:
  schemas:

    TscaiInputContainer:
      $ref: 'https://forge.3gpp.org/rep/all/5G_APIs/raw/REL-16/TS29514_Npcf_PolicyAuthorization.yaml#/components/schemas/TscaiInputContainer'

    RedirectInformation:
      $ref: 'https://forge.3gpp.org/rep/all/5G_APIs/raw/REL-16/TS29512_Npcf_SMPolicyControl.yaml#/components/schemas/RedirectInformation'

    BitRateRm:
      $ref: 'https://forge.3gpp.org/rep/all/5G_APIs/raw/REL-16/TS29571_CommonData.yaml#/components/schemas/BitRateRm'
