openapi: 3.0.1
info:
  title: 3GPP Edge NRM
  version: 17.1.0
  description: >-
    OAS 3.0.1 specification of the Edge NRM
    © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
externalDocs:
  description: 3GPP TS 28.538; Edge NRM
  url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.538/
paths: {}
components:
  schemas:
  
#-------- Definition of types-----------------------------------------------------
    ServingLocation:
      type: object
      properties:
        geographicalLocation:
          $ref: '#/components/schemas/GeoLoc'
        topologicalLocation:
          $ref: 'genericNrm.yaml#/components/schemas/TopologicalLocation'

    TopologicalLocation:
      type: object
      properties:
        cellIdList:
          $ref: '#/components/schemas/CellIdList'
        trackingAreaIdList:
          $ref: '#/components/schemas/TrackingAreaIdList'
        servingPLMN:
          $ref: '#/components/schemas/PLMNId'


    CellIdList:
      type: array
      items:
        $ref: '#/components/schemas/CellId'

    CellId:
      type: integer
      description: represent the ID of a NR cell

    TrackingAreaIdList:
      type: array
      items:
        $ref: '#/components/schemas/TrackingAreaId’

    TrackingAreaId:
      type: object
        $ref: 'genericNrm.yaml#/components/schemas/TAI'

    GeoLoc:
      type: object
      properties:
        geographicalCoordinates:
          $ref: '#/components/schemas/GeographicalCoordinates'

        civicLocations:
          type: string

    GeographicalCoordinates:
      type: object
      properties:
        lattitude:
          type: integer
        longitude:
          type: integer

    EDNConnectionInfo:
      type: object
      properties:
        dNN:
          type: string
        eDNServiceArea:
          $ref: '#/components/schemas/ServingLocation'

    SoftwareImageInfo:
      type: object
      properties:
        minimumDisk:
          type: integer
        minimumRAM:
          type: integer
        swImageRef:
          type: string
          description: indicates the reference to the actual software image that is represented by URL (see clause 7.1.6.5 in in ETSI NFV IFA-011 [7]).


#-------- Definition of concrete IOCs --------------------------------------------

    SubNetwork-Single:
      allOf:
        - $ref: 'genericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              allOf:
                - $ref: 'genericNrm.yaml#/components/schemas/SubNetwork-Attr'
        - type: object
          properties:
            Subnetwork:
              $ref: 'genericNrm.yaml#/components/schemas/SubNetwork-Multiple'
            ECSFunction:
              $ref: '#/components/schemas/ECSFunction-Multiple'
            EdgeDataNetwork:
              $ref: '#/components/schemas/EdgeDataNetwork-Multiple'
        - $ref: 'genericNrm.yaml#/components/schemas/SubNetwork-ncO'

    EdgeDataNetwork-Single:
      allOf:
        - $ref: 'genericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            EASFunction:
              $ref: '#/components/schemas/EASFunction-Multiple'
            EESFunction:
              $ref: '#/components/schemas/EESFunction-Multiple'
   
    EASFunction-Single:
      allOf:
        - $ref: 'genericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              allOf:
                - $ref: 'genericNrm.yaml#/components/schemas/ManagedFunction-Attr'
                - type: object
                  properties:
                    eASIdentifier:
                      type: string
                    eASAddress:
                      type: string
                    eASRequirementsRef:
                      $ref: '#/components/schemas/EASRequirements'
        - $ref: 'genericNrm.yaml#/components/schemas/SubNetwork-ncO'
    EESFunction-Single:
      allOf:
        - $ref: 'genericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              allOf:
                - $ref: 'genericNrm.yaml#/components/schemas/ManagedFunction-Attr'
                - type: object
                  properties:
                    eESIdentifier:
                      type: string
                - $ref: 'genericNrm.yaml#/components/schemas/SubNetwork-ncO'

    ECSFunction-Single:
      allOf:
        - $ref: 'genericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              allOf:
                - $ref: 'genericNrm.yaml#/components/schemas/ManagedFunction-Attr'
                - type: object
                  properties:
                    eCSAddress:
                      type: string
                    providerIdentifier:
                      type: string
                    eDNConnectionInfo:
                      $ref: '#/components/schemas/EDNConnectionInfo'
                    softwareImageInfo:
                      $ref: '#/components/schemas/SoftwareImageInfo'
        - $ref: 'genericNrm.yaml#/components/schemas/SubNetwork-ncO'

    EASRequirements:
      allOf:
        - $ref: 'genericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            requiredEASservingLocation:
              $ref: '#/components/schemas/ServingLocation'
            softwareImageInfo:
              $ref: '#/components/schemas/SoftwareImageInfo'


#-------- Definition of JSON arrays for name-contained IOCs ----------------------                               
          
    SubNetwork-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/SubNetwork-Single'
    EASFunction-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/EASFunction-Single'   
    ECSFunction-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/ECSFunction-Single'
    EESFunction-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/EESFunction-Single'
    EdgeDataNetwork-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/EdgeDataNetwork-Single'
        
#--------------------------------- Definition ------------------------------------                          

    resources-edgeNrm:
      oneOf:
        - $ref: '#/components/schemas/SubNetwork-Single'
        - $ref: '#/components/schemas/EASFunction-Single'
        - $ref: '#/components/schemas/ECSFunction-Single'
        - $ref: '#/components/schemas/EESFunction-Single'
        - $ref: '#/components/schemas/EdgeDataNetwork-Single'
