openapi: 3.0.1
info:
  title: Generic NRM
  version: 16.3.0
  description: >-
    OAS 3.0.1 specification of the Generic NRM
    @ 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
externalDocs:
  description: 3GPP TS 28.623 V16.3.0; Generic NRM
  url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.623/
paths: {}
components:
  schemas:

#-------- Definition of types-----------------------------------------------------

    Dn:
      type: string
      maxLength: 400
    DnList:
      type: array
      items:
        $ref: '#/components/schemas/Dn'
    Mcc:
      type: string
      pattern: '^[0-9]{3}$'
    AdministrativeState:
      type: string
      enum:
        - LOCKED
        - SHUTTING_DOWN
        - UNLOCKED
    OperationalState:
      type: string
      enum:
        - ENABLED
        - DISABLED
    UsageState:
      type: string
      enum:
        - IDEL
        - ACTIVE
        - BUSY
    RegistrationState:
      type: string
      enum:
        - REGISTERED
        - DEREGISTERED
    SetOfMcc:
      type: array
      items:
        $ref: '#/components/schemas/Mcc'
    ManagedElementType:
      type: string
    ManagedElementTypeList:
      type: array
      items:
        $ref: '#/components/schemas/ManagedElementType'
    VnfParameter:
      type: object
      properties:
        vnfInstanceId:
          type: string
        vnfdId:
          type: string
        flavourId:
          type: string
        autoScalable:
          type: boolean
    VnfParametersList:
      type: array
      items:
        $ref: '#/components/schemas/VnfParameter'
    SiteLatitude:
      type: number
      format: float
      minimum: -90
      maximum: 90
    SiteLongitude:
      type: number
      format: float
      minimum: -180
      maximum: 180
    PeeParameter:
      type: object
      properties:
        siteIdentification:
          type: string
        siteDescription:
          type: string
        siteLatitude:
          $ref: '#/components/schemas/SiteLatitude'
        siteLongitude:
          $ref: '#/components/schemas/SiteLongitude'
        equipmentType:
          type: string
        environmentType:
          type: string
        powerInterface:
          type: string
    PeeParametersList:
      type: array
      items:
        $ref: '#/components/schemas/PeeParameter'
    MonitoringGPList:
      type: array
      items:
        type: integer
    ThresholdInfoList:
      type: array
      items:
        $ref: '#/components/schemas/ThresholdInfo'
    ThresholdInfo:
      type: object
      properties:
        measurementType:
          type: string
        direction:
          $ref: '#/components/schemas/Direction'
        thresholdPack:
          $ref: '#/components/schemas/ThresholdPack'
    Direction:
      enum:
        - Increasing
        - Decreasing
    ThresholdPack:
      type: array
      items:
        $ref: '#/components/schemas/ThresholdPackElement'
    ThresholdPackElement:
      type: object
      properties:
        thresholdLevel:
          type: integer
        thresholdValue:
          type: number
        hysteresis:
          type: number
    Operation:
      type: object
      properties:
        name:
          type: string
        allowedNFTypes:
          $ref: '#/components/schemas/NFType'
        operationSemantics:
          $ref: '#/components/schemas/OperationSemantics'
    OperationList:
      type: array
      items:
        $ref: '#/components/schemas/Operation'
    NFType:
      type: string
      description: ' NF name defined in TS 23.501'
      enum:
        - NRF
        - UDM
        - AMF
        - SMF
        - AUSF
        - NEF
        - PCF
        - SMSF
        - NSSF
        - UDR
        - LMF
        - GMLC
        - 5G_EIR
        - SEPP
        - UPF
        - N3IWF
        - AF
        - UDSF
        - DN
    Fqdn:
      type: string
    OperationSemantics:
      type: string
      enum:
        - REQUEST_RESPONSE
        - SUBSCRIBE_NOTIFY
    SAP:
      type: object
      properties:
        host:
          $ref: '#/components/schemas/HostAddr'
        port:
          type: integer
    NFServiceType:
      type: string
      enum:
        - Namf_Communication
        - Namf_EventExposure
        - Namf_MT
        - Namf_Location
        - Nsmf_PDUSession
        - Nsmf_EventExposure
        - Others
    HostAddr:
      oneOf:
        - $ref: '#/components/schemas/Ipv4Addr'
        - $ref: '#/components/schemas/Ipv6Addr'
        - $ref: '#/components/schemas/Fqdn'
    Ipv4Addr:
      type: string
      pattern: '^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$'
      example: '198.51.100.1'
    Ipv4AddrRm:
      type: string
      pattern: '^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$'
      example: '198.51.100.1'
      nullable: true
    Ipv6Addr:
      type: string
      allOf:
        - pattern: '^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))$'
        - pattern: '^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))$'
      example: '2001:db8:85a3::8a2e:370:7334'
    Ipv6AddrRm:
      type: string
      allOf:
        - pattern: '^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))$'
        - pattern: '^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))$'
      example: '2001:db8:85a3::8a2e:370:7334'
      nullable: true
    Ipv6Prefix:
      type: string
      allOf:
        - pattern: '^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))(\/(([0-9])|([0-9]{2})|(1[0-1][0-9])|(12[0-8])))$'
        - pattern: '^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))(\/.+)$'
      example: '2001:db8:abcd:12::0/64'
    Uri:
      type: string
    TransportProtocol:
      anyOf:
        - type: string
          enum:
            - TCP
        - type: string
    Measurements:
      type: object
      properties:
        measurementTypes:
          type: array
          items:
            type: string
        gPs:
          type: array
          items:
            type: integer
    MeasurementsList:
      type: array
      items:
        $ref: '#/components/schemas/Measurements'
      nullable: true
    KPIs:
      type: object
      properties:
        kPINames:
          type: array
          items:
            type: string
        gPs:
          type: array
          items:
            type: integer
    KPIsList:
      type: array
      items:
        $ref: '#/components/schemas/KPIs'
      nullable: true
    Scope:
      type: object
      properties:
        scopeType:
          type: string
          enum:
            - BASE_ONLY
            - BASE_ALL
            - BASE_NTH_LEVEL
            - BASE_SUBTREE
        scopeLevel:
          type: integer

#-------- Definition of abstract IOC Top -----------------------------------------

    Top-Attr:
      type: object
      properties:
        id:
          type: string

#-------- Definition of IOCs with new name-containments defined in other TS ------

    SubNetwork-Attr:
      type: object
      properties:
        dnPrefix:
          type: string
        userLabel:
          type: string
        userDefinedNetworkType:
          type: string
        setOfMcc:
          $ref: '#/components/schemas/SetOfMcc'
        priorityLabel:
          type: integer
        measurementsList:
          $ref: '#/components/schemas/MeasurementsList'
        kPIsList:
          $ref: '#/components/schemas/KPIsList'
    ManagedElement-Attr:
      type: object
      properties:
        dnPrefix:
          type: string
        managedElementTypeList:
          $ref: '#/components/schemas/ManagedElementTypeList'
        userLabel:
          type: string
        locationName:
          type: string
        managedBy:
          $ref: '#/components/schemas/DnList'
        vendorName:
          type: string
        userDefinedState:
          type: string
        swVersion:
          type: string
        priorityLabel:
          type: integer
        measurementsList:
          $ref: '#/components/schemas/MeasurementsList'

    SubNetwork-ncO:
      type: object
      properties:
        ManagementNode:
          $ref: '#/components/schemas/ManagementNode-Multiple'
        MeContext:
          $ref: '#/components/schemas/MeContext-Multiple'
        MeasurementControl:
          $ref: '#/components/schemas/MeasurementControl-Multiple'
        ThresholdMonitor:
          $ref: '#/components/schemas/ThresholdMonitor-Multiple'
        ThresholdMonitoringCapability:
          $ref: '#/components/schemas/ThresholdMonitoringCapability-Single'
        NtfSubscriptionControl:
          $ref: '#/components/schemas/NtfSubscriptionControl-Multiple'
    ManagedElement-ncO:
      type: object
      properties:
        MeasurementControl:
          $ref: '#/components/schemas/MeasurementControl-Multiple'
        ThresholdMonitor:
          $ref: '#/components/schemas/ThresholdMonitor-Multiple'
        ThresholdMonitoringCapability:
          $ref: '#/components/schemas/ThresholdMonitoringCapability-Single'
        NtfSubscriptionControl:
          $ref: '#/components/schemas/NtfSubscriptionControl-Multiple'

#-------- Definition of abstract IOCs --------------------------------------------

    ManagedFunction-Attr:
      type: object
      properties:
        userLabel:
          type: string
        vnfParametersList:
          $ref: '#/components/schemas/VnfParametersList'
        peeParametersList:
          $ref: '#/components/schemas/PeeParametersList'
        priorityLabel:
          type: integer
        measurementsList:
          $ref: '#/components/schemas/MeasurementsList'
    EP_RP-Attr:
      type: object
      properties:
        userLabel:
          type: string
        farEndEntity:
          type: string
        measurementsList:
          $ref: '#/components/schemas/MeasurementsList'

    ManagedFunction-ncO:
      type: object
      properties:
        MeasurementControl:
          $ref: '#/components/schemas/MeasurementControl-Multiple'
        ThresholdMonitor:
          $ref: '#/components/schemas/ThresholdMonitor-Multiple'
        ThresholdMonitoringCapability:
          $ref: '#/components/schemas/ThresholdMonitoringCapability-Single'
        ManagedNFService:
          $ref: '#/components/schemas/ManagedNFService-Multiple'

#-------- Definition of concrete IOCs --------------------------------------------

    ManagedNFService-Single:
      allOf:
        - $ref: '#/components/schemas/Top-Attr'
        - type: object
          properties:
            attributes:
              type: object
              properties:
                userLabel:
                  type: string
                nFServiceType:
                  $ref: '#/components/schemas/NFServiceType'
                sAP:
                  $ref: '#/components/schemas/SAP'
                operations:
                  $ref: '#/components/schemas/OperationList'
                administrativeState:
                  $ref: '#/components/schemas/AdministrativeState'
                operationalState:
                  $ref: '#/components/schemas/OperationalState'
                usageState:
                  $ref: '#/components/schemas/UsageState'
                registrationState:
                  $ref: '#/components/schemas/RegistrationState'
    ManagementNode-Single:
      allOf:
        - $ref: '#/components/schemas/Top-Attr'
        - type: object
          properties:
            attributes:
              type: object
              properties:
                userLabel:
                  type: string
                managedElements:
                  $ref: '#/components/schemas/DnList'
                vendorName:
                  type: string
                userDefinedState:
                  type: string
                locationName:
                  type: string
                swVersion:
                  type: string
    MeContext-Single:
      allOf:
        - $ref: '#/components/schemas/Top-Attr'
        - type: object
          properties:
            attributes:
              type: object
              properties:
                dnPrefix:
                  type: string
    MeasurementControl-Single:
      allOf:
        - $ref: '#/components/schemas/Top-Attr'
        - type: object
          properties:
            attributes:
              type: object
              properties:
                pMAdministrativeState:
                  $ref: '#/components/schemas/AdministrativeState'
                pMOperationalState:
                  $ref: '#/components/schemas/OperationalState'
                defaultFileBasedGp:
                  type: integer
                defaultFileReportPeriod:
                  type: integer
                defaultStreamBasedGp:
                  type: integer
                defaultFileLocation:
                  type: string
                defaultStreamTarget:
                 type: string
            MeasurementReader:
             $ref: '#/components/schemas/MeasurementReader-Multiple'
    MeasurementReader-Single:
      allOf:
        - $ref: '#/components/schemas/Top-Attr'
        - type: object
          properties:
            attributes:
              type: object
              properties:
                measurementTypes:
                  type: string
                fileBasedGp:
                  type: integer
                fileReportingPeriod:
                  type: integer
                streamBasedGp:
                  type: integer
                fileLocation:
                  type: string
                streamTarget:
                  type: string
                managementObjectDNsBasic:
                  $ref: '#/components/schemas/DnList'
                managementObjectDNs:
                  $ref: '#/components/schemas/DnList'
    ThresholdMonitoringCapability-Single:
      allOf:
        - $ref: '#/components/schemas/Top-Attr'
        - type: object
          properties:
            attributes:
              type: object
              properties:
                supportedMonitoringGPs:
                  $ref: '#/components/schemas/MonitoringGPList'
    ThresholdMonitor-Single:
      allOf:
        - $ref: '#/components/schemas/Top-Attr'
        - type: object
          properties:
            attributes:
              type: object
              properties:
                thresholdInfoList:
                  $ref: '#/components/schemas/ThresholdInfoList'
                monitoringGP:
                  type: integer
                monitoringNotifTarget:
                  type: string
                monitoredIOCName:
                  type: string
                monitoredObjectDNs:
                  $ref: '#/components/schemas/DnList'
    NtfSubscriptionControl-Single:
      allOf:
        - $ref: '#/components/schemas/Top-Attr'
        - type: object
          properties:
            attributes:
              type: object
              properties:
                notificationRecipientAddress:
                  $ref: '#/components/schemas/Uri'
                notificationTypes:
                  type: string
                scope:
                  $ref: '#/components/schemas/Scope'
                notificationFilter:
                  type: string
            HeartbeatControl:
              $ref: '#/components/schemas/HeartbeatControl-Single'
    HeartbeatControl-Single:
      allOf:
        - $ref: '#/components/schemas/Top-Attr'
        - type: object
          properties:
            attributes:
              type: object
              properties:
                heartbeatNtfPeriod:
                  type: integer
                triggerHeartbeatNtf:
                  type: boolean

#-------- Definition of JSON arrays for name-contained IOCs ----------------------

    ManagedNFService-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/ManagedNFService-Single'
    ManagementNode-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/ManagementNode-Single'
    MeContext-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/MeContext-Single'
    MeasurementControl-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/MeasurementControl-Single'
    MeasurementReader-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/MeasurementReader-Single'
    ThresholdMonitor-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/ThresholdMonitor-Single'
    NtfSubscriptionControl-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/NtfSubscriptionControl-Single'

#-------- Definitions in TS 28.623 for TS 28.532 ---------------------------------

    resources-genericNrm:
      oneOf:
       - $ref: '#/components/schemas/ManagementNode-Single'
       - $ref: '#/components/schemas/MeContext-Single'

       - $ref: '#/components/schemas/ManagedNFService-Single'

       - $ref: '#/components/schemas/MeasurementControl-Single'
       - $ref: '#/components/schemas/MeasurementReader-Single'

       - $ref: '#/components/schemas/ThresholdMonitoringCapability-Single'
       - $ref: '#/components/schemas/ThresholdMonitor-Single'

       - $ref: '#/components/schemas/NtfSubscriptionControl-Single'
       - $ref: '#/components/schemas/HeartbeatControl-Single'

