openapi: 3.0.1
info:
  title: TS 28.532 File data reporting Service
  version: 16.6.0
  description: >-
    OAS 3.0.1 specification of the File data reporting Management Service © 2020,
    3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All
    rights reserved.
externalDocs:
  description: 3GPP TS 28.532 V16.5.0; Generic management services
  url: 'http://www.3gpp.org/ftp/Specs/archive/28_series/28.532/'
paths: {}

