openapi: 3.0.1
info:
  title: Slice NRM
  version: 17.3.0
  description: >-
    OAS 3.0.1 specification of the Slice NRM
    @ 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
externalDocs:
  description: 3GPP TS 28.541; 5G NRM, Slice NRM
  url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.541/
paths: {}
components:
  schemas:

#------------ Type definitions ---------------------------------------------------

    Float:
      type: number
      format: float
    MobilityLevel:
      type: string
      enum:
        - STATIONARY
        - NOMADIC
        - RESTRICTED MOBILITY
        - FULLY MOBILITY
    SynAvailability:
      type: string
      enum:
        - NOT SUPPORTED
        - BETWEEN BS AND UE
        - BETWEEN BS AND UE & UE AND UE
    PositioningAvailability:
      type: array
      items:
        type: string
        enum:
          - CIDE-CID
          - OTDOA
          - RF FINGERPRINTING
          - AECID
          - HYBRID POSITIONING
          - NET-RTK
    Predictionfrequency:
      type: string
      enum:
        - PERSEC
        - PERMIN
        - PERHOUR
    SharingLevel:
      type: string
      enum:
        - SHARED
        - NON-SHARED

    NetworkSliceSharingIndicator:
      type: string
      enum:
        - SHARED
        - NON-SHARED

    ServiceType:
      type: string
      enum:
        - eMBB
        - RLLC
        - MIoT
        - V2X
    SliceSimultaneousUse:
      type: string
      enum:
        - ZERO
        - ONE
        - TWO
        - THREE
        - FOUR
    Category:
      type: string
      enum:
        - CHARACTER
        - SCALABILITY
    Tagging:
      type: array
      items:
        type: string
        enum:
          - PERFORMANCE
          - FUNCTION
          - OPERATION
    Exposure:
      type: string
      enum:
        - API
        - KPI
    ServAttrCom:
      type: object
      properties:
        category:
          $ref: '#/components/schemas/Category'
        tagging:
          $ref: '#/components/schemas/Tagging'
        exposure:
          $ref: '#/components/schemas/Exposure'
    Support:
      type: string
      enum:
        - NOT SUPPORTED
        - SUPPORTED
    DelayTolerance:
      type: object
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        support:
          $ref: '#/components/schemas/Support'
    DeterministicComm:
      type: object
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        availability:
          $ref: '#/components/schemas/Support'
        periodicityList:
          type: string
    XLThpt:
      type: object
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        guaThpt:
          $ref: '#/components/schemas/Float'
        maxThpt:
          $ref: '#/components/schemas/Float'
    MaxPktSize:
      type: object
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        maxsize:
          type: integer
    MaxNumberofPDUSessions:
      type: object
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        nOofPDUSessions:
          type: integer
    KPIMonitoring:
      type: object
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        kPIList:
          type: string
    NBIoT:
      type: object
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        support:
          $ref: '#/components/schemas/Support'
    Synchronicity:
      type: object
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        availability:
          $ref: '#/components/schemas/SynAvailability'
        accuracy:
          $ref: '#/components/schemas/Float'
    SynchronicityRANSubnet:
      type: object
      properties:
        availability:
          $ref: '#/components/schemas/SynAvailability'
        accuracy:
          $ref: '#/components/schemas/Float'
    Positioning:
      type: object
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        availability:
          $ref: '#/components/schemas/PositioningAvailability'
        predictionfrequency:
          $ref: '#/components/schemas/Predictionfrequency'
        accuracy:
          $ref: '#/components/schemas/Float'
    PositioningRANSubnet:
      type: object
      properties:
        availability:
          $ref: '#/components/schemas/PositioningAvailability'
        predictionfrequency:
          $ref: '#/components/schemas/Predictionfrequency'
        accuracy:
          $ref: '#/components/schemas/Float'     
    UserMgmtOpen:
      type: object
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        support:
          $ref: '#/components/schemas/Support'
    V2XCommModels:
      type: object
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        v2XMode:
          $ref: '#/components/schemas/Support'
    TermDensity:
      type: object
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        density:
          type: integer
    NsInfo:
      type: object
      properties:
        nsInstanceId:
          type: string
        nsName:
          type: string
    EmbbEEPerfReq:
      type: integer
    UrllcEEPerfReq:
      type: integer
    MIoTEEPerfReq:
      type: object
      properties:
        KpiType:
          type: string
          enum:
            - MAXREGSUBS
            - MEANACTIVEUES
        Req:
          type: integer
    EEPerfReq:
      oneOf:
        - $ref: '#/components/schemas/EmbbEEPerfReq'
        - $ref: '#/components/schemas/UrllcEEPerfReq'
        - $ref: '#/components/schemas/MIoTEEPerfReq'
    EnergyEfficiency:
      type: object
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        performance:
          $ref: '#/components/schemas/EEPerfReq'      
    CNSliceSubnetProfile:
      type: object
      properties:
        maxNumberofUEs:
          type: integer
        latency:
          type: integer
        dLThptPerSliceSubnet:
          $ref: '#/components/schemas/XLThpt'
        dLThptPerUE:
          $ref: '#/components/schemas/XLThpt'
        uLThptPerSliceSubnet:
          $ref: '#/components/schemas/XLThpt'
        uLThptPerUE:
          $ref: '#/components/schemas/XLThpt'
        maxNumberOfPDUSessions:
          type: integer
        coverageAreaTAList:
          type: integer
        resourceSharingLevel:
          $ref: '#/components/schemas/SharingLevel'
        maxPktSize:
          type: integer
        delayTolerance:
          $ref: '#/components/schemas/DelayTolerance'
        synchronicity:
          $ref: '#/components/schemas/SynchronicityRANSubnet'
        sliceSimultaneousUse:
          $ref: '#/components/schemas/SliceSimultaneousUse'
        reliability:
          type: string
        energyEfficiency:
          type: integer 
        deterministicComm:
          $ref: '#/components/schemas/DeterministicComm'
    RANSliceSubnetProfile:
      type: object
      properties:
        coverageAreaTAList:
          type: integer
        uEMobilityLevel:
          $ref: '#/components/schemas/MobilityLevel'
        resourceSharingLevel:
          $ref: '#/components/schemas/SharingLevel'
        maxNumberofUEs:
          type: integer
        activityFactor:
          type: integer
        dLThptPerUE:
          $ref: '#/components/schemas/XLThpt'
        uLThptPerUE:
          $ref: '#/components/schemas/XLThpt'
        uESpeed:
          type: integer
        reliability:
          type: string
        serviceType:
          $ref: '#/components/schemas/ServiceType'
        maxPktSize:
          type: integer
        delayTolerance:
          $ref: '#/components/schemas/DelayTolerance'
        positioning:
          $ref: '#/components/schemas/PositioningRANSubnet'
        sliceSimultaneousUse:
          $ref: '#/components/schemas/SliceSimultaneousUse'
        energyEfficiency:
          type: integer
        termDensity:
          $ref: '#/components/schemas/TermDensity'
        survivalTime:
          type: string
        synchronicity:
          $ref: '#/components/schemas/SynchronicityRANSubnet'
        deterministicComm:
          $ref: '#/components/schemas/DeterministicComm'
    TopSliceSubnetProfile:
      type: object
      properties:
        coverageArea:
          type: string
        latency:
          type: integer
        maxNumberofUEs:
          type: integer
        dLThptPerSliceSubnet:
          $ref: '#/components/schemas/XLThpt'
        dLThptPerUE:
          $ref: '#/components/schemas/XLThpt'
        uLThptPerSliceSubnet:
          $ref: '#/components/schemas/XLThpt'
        uLThptPerUE:
          $ref: '#/components/schemas/XLThpt'
        maxPktSize:
          type: integer
        maxNumberOfPDUSessions:
          type: integer
        sliceSimultaneousUse:
          $ref: '#/components/schemas/SliceSimultaneousUse'
        energyEfficiency:
          type: integer
        synchronicity:
          $ref: '#/components/schemas/Synchronicity'
        delayTolerance:
          $ref: '#/components/schemas/DelayTolerance'
        positioning:
          $ref: '#/components/schemas/Positioning'  
        termDensity:
          $ref: '#/components/schemas/TermDensity'
        activityFactor:
          type: integer
        coverageAreaTAList:
          type: integer
        resourceSharingLevel:
          $ref: '#/components/schemas/SharingLevel'
        uEMobilityLevel:
          $ref: '#/components/schemas/MobilityLevel'
        uESpeed:
          type: integer
        reliability:
          type: string
        serviceType:
          $ref: '#/components/schemas/ServiceType'
        deterministicComm:
          $ref: '#/components/schemas/DeterministicComm'
        survivalTime:
          type: string

    ServiceProfile:
      type: object
      properties:
          serviceProfileId: 
            type: string
          plmnInfoList:
            $ref: 'nrNrm.yaml#/components/schemas/PlmnInfoList'
          maxNumberofUEs:
            type: number
          latency:
            type: number
          uEMobilityLevel:
            $ref: '#/components/schemas/MobilityLevel'
          sst:
            $ref: 'nrNrm.yaml#/components/schemas/Sst'
          networkSliceSharingIndicator:
            $ref: '#/components/schemas/NetworkSliceSharingIndicator'
          availability:
            type: number
          delayTolerance:
            $ref: '#/components/schemas/DelayTolerance'
          deterministicComm:
            $ref: '#/components/schemas/DeterministicComm'
          dLThptPerSlice:
            $ref: '#/components/schemas/XLThpt'
          dLThptPerUE:
            $ref: '#/components/schemas/XLThpt'
          uLThptPerSlice:
            $ref: '#/components/schemas/XLThpt'
          uLThptPerUE:
            $ref: '#/components/schemas/XLThpt'
          maxPktSize:
            $ref: '#/components/schemas/MaxPktSize'
          maxNumberofPDUSessions:
            $ref: '#/components/schemas/MaxNumberofPDUSessions'
          kPIMonitoring:
            $ref: '#/components/schemas/KPIMonitoring'
          nBIoT:
            $ref: '#/components/schemas/NBIoT'
          synchronicity:
            $ref: '#/components/schemas/Synchronicity'
          positioning:
            $ref: '#/components/schemas/Positioning'
          userMgmtOpen:
            $ref: '#/components/schemas/UserMgmtOpen'
          v2XModels:
            $ref: '#/components/schemas/V2XCommModels'
          coverageArea:
            type: string
          termDensity:
            $ref: '#/components/schemas/TermDensity'
          activityFactor:
            $ref: '#/components/schemas/Float'
          uESpeed:
            type: integer
          jitter:
            type: integer
          survivalTime:
            type: string
          reliability:
            type: string
          maxDLDataVolume:
            type: string
          maxULDataVolume:
            type: string
          sliceSimultaneousUse:
            $ref: '#/components/schemas/SliceSimultaneousUse'
          energyEfficiency:
            $ref: '#/components/schemas/EnergyEfficiency'
    SliceProfile:
      type: object
      properties:
          serviceProfileId: 
            type: string
          plmnInfoList:
            $ref: 'nrNrm.yaml#/components/schemas/PlmnInfoList'
          cNSliceSubnetProfile:
            $ref: '#/components/schemas/CNSliceSubnetProfile'
          rANSliceSubnetProfile:
            $ref: '#/components/schemas/RANSliceSubnetProfile'
          topSliceSubnetProfile:
            $ref: '#/components/schemas/TopSliceSubnetProfile'

    IpAddress:
      oneOf:
        - $ref: 'genericNrm.yaml#/components/schemas/Ipv4Addr'
        - $ref: 'genericNrm.yaml#/components/schemas/Ipv6Addr'
    
    LogicInterfaceInfo:
      type: object
      properties:
         logicalInterfceType:
           type: string
           enum: 
            - VLAN
            - MPLS
            - Segment
         logicalInterfceId:
           type: string

    ServiceProfileList:
       type: array
       items:
        $ref: '#/components/schemas/ServiceProfile'
            
    SliceProfileList:
      type: array
      items:
        $ref: '#/components/schemas/SliceProfile'

#------------ Definition of concrete IOCs ----------------------------------------
    SubNetwork-Single:
      allOf:
        - $ref: 'genericNrm.yaml#/components/schemas/Top-Attr'
        - type: object
          properties:
            attributes:
              allOf:
                - $ref: 'genericNrm.yaml#/components/schemas/SubNetwork-Attr'
        - $ref: 'genericNrm.yaml#/components/schemas/SubNetwork-ncO'
        - type: object
          properties:
            SubNetwork:
              $ref: '#/components/schemas/SubNetwork-Multiple'
            NetworkSlice:
              $ref: '#/components/schemas/NetworkSlice-Multiple'
            NetworkSliceSubnet:
              $ref: '#/components/schemas/NetworkSliceSubnet-Multiple'
            EP_Transport:
              $ref: '#/components/schemas/EP_Transport-Multiple'

    NetworkSlice-Single:
      allOf:
        - $ref: 'genericNrm.yaml#/components/schemas/Top-Attr'
        - type: object
          properties:
            attributes:
              allOf:
                - type: object
                  properties:
                    networkSliceSubnetRef:
                      $ref: 'genericNrm.yaml#/components/schemas/Dn'
                    operationalState:
                      $ref: 'genericNrm.yaml#/components/schemas/OperationalState'
                    administrativeState:
                      $ref: 'genericNrm.yaml#/components/schemas/AdministrativeState'
                    serviceProfileList:
                      $ref: '#/components/schemas/ServiceProfileList'

    NetworkSliceSubnet-Single:
      allOf:
        - $ref: 'genericNrm.yaml#/components/schemas/Top-Attr'
        - type: object
          properties:
            attributes:
              allOf:
                - type: object
                  properties:
                    managedFunctionRefList:
                      $ref: 'genericNrm.yaml#/components/schemas/DnList'
                    networkSliceSubnetRefList:
                      $ref: 'genericNrm.yaml#/components/schemas/DnList'
                    operationalState:
                      $ref: 'genericNrm.yaml#/components/schemas/OperationalState'
                    administrativeState:
                      $ref: 'genericNrm.yaml#/components/schemas/AdministrativeState'
                    nsInfo:
                      $ref: '#/components/schemas/NsInfo'
                    sliceProfileList:
                      $ref: '#/components/schemas/SliceProfileList'
                    epTransportRefList:
                      $ref: 'genericNrm.yaml#/components/schemas/DnList'

    EP_Transport-Single:
      allOf:
        - $ref: 'genericNrm.yaml#/components/schemas/Top-Attr'
        - type: object
          properties:
            attributes:
              type: object
              properties:
                ipAddress:
                  $ref: '#/components/schemas/IpAddress'
                logicInterfaceInfo:
                  $ref: '#/components/schemas/LogicInterfaceInfo'
                nextHopInfo:
                  type: string 
                qosProfile:
                  type: string 
                epApplicationRefs:
                  $ref: 'genericNrm.yaml#/components/schemas/DnList'

#-------- Definition of JSON arrays for name-contained IOCs ----------------------
    SubNetwork-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/SubNetwork-Single'

    NetworkSlice-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/NetworkSlice-Single'

    NetworkSliceSubnet-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/NetworkSliceSubnet-Single'
                      
    EP_Transport-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/EP_Transport-Single'

#------------ Definitions in TS 28.541 for TS 28.532 -----------------------------

    resources-sliceNrm:
      oneOf:
       - $ref: '#/components/schemas/SubNetwork-Single'
       - $ref: '#/components/schemas/NetworkSlice-Single'
       - $ref: '#/components/schemas/NetworkSliceSubnet-Single'
       - $ref: '#/components/schemas/EP_Transport-Single'
